name: Update Go version

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-go-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable

      - name: Update go version in go.mod
        run: go get go@$(go env GOVERSION | sed 's/go//')

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "chore(deps): update go version"
          title: "chore(deps): update go version"
          body: |
            Automated go version updates.
          branch: update-go-version
          labels: dependencies
